---
- name: Install Git, JDK, Maven, clone Git repository
  hosts: mvn
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Ensure git package is present
      apt:
        name: git
        state: present

    - name: Ensure default-jdk package is present
      apt:
        name: openjdk-11-jre-headless
        state: present

    - name: Ensure maven package is present
      apt:
        name: maven
        state: present

    - name: Setup Git repository
      git:
        repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest=/root/complete

    - name: Build app
      shell: mvn package chdir="/root/complete"



- name: install Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day


    - name: Ensure tomcat package is present
      apt:
        name: tomcat9
        state: present

    - name: Ensure tomcat service is started
      service:
        name: tomcat9
        state: started

    - name: Transfer file from mvn to web
      synchronize:
        src: /root/complete/target/hello-1.0.war
        dest: /path/on/server_b
      delegate_to: /usr/local/tomcat/webapps